### ISSUE TITLE
The caching architecture is a mess

### ISSUE THREAD

**Issue by MarinAtanasov** [aspnet/Caching#107]
Hey guys,

I have been trying to figure out the hierarchy around the caching framework.
So far everything seems to be a huge mess:
1. LocalCache implements IDistributedCache which does not make any sense.
2. IDistributedCache works with byte[] but there is no binary serializer in .NET Core.
3. MemoryCache implements IMemoryCache which does not inherit from a more generic caching interface.

I have been trying to wrap a local in-memory cache which I should be able to replace by changing the cache which I am using. However, I find it quite difficult to use LocalCache because it requires a binary serializer which is an unnecessary overhead and there isn't a build-in one in .NET Core anyway. I cannot wrap directly MemoryCache because the interface it implements basically means that I will be stuck using an in-memory cache and I will not be able to switch at a later point.

I am sorry if I sound too harsh but the current architecture is a mess. Please fix/rewrite this architecture before you release a final version and we get stuck with something which cannot be changed because it will require breaking changes.

**Comment by davidfowl** [comment]
No problem. I'll explain the architecture by answering your observations.

There are 2 core interfaces that your application can used when caching, IDistributedCache and IMemoryCache. As you've observed they are *very* different and that is intentional. The major differences are the fact that IDistributedCache is async and requires a serialization mechanism. They are used for different things but that should be obvious from the interfaces themselves. The IMemoryCache represents in memory storage, it handles things like memory pressure (at least the default implementation does)

> 1. LocalCache implements IDistributedCache which does not make any sense.

Sure it does, LocalCache is an implementation of IDistributedCache that runs in memory. The key thing to look at is the interface. If you intend to use the cache to store things in a distributed store, then it's the interface that matters the most.

> IDistributedCache works with byte[] but there is no binary serializer in .NET Core.

.NET Core has BinaryWriter and BinaryReader but that's besides the point. In time all of the popular serializers like protobuf, bond etc. will be ported to .NET Core.

> 3. MemoryCache implements IMemoryCache which does not inherit from a more generic caching interface.

Don't know why it would need to.

> I have been trying to wrap a local in-memory cache which I should be able to replace by changing the cache which I am using. However, I find it quite difficult to use LocalCache because it requires a binary serializer which is an unnecessary overhead and there isn't a build-in one in .NET Core anyway. I cannot wrap directly MemoryCache because the interface it implements basically means that I will be stuck using an in-memory cache and I will not be able to switch at a later point.

What exactly are you trying to do. Maybe you used the wrong interface.

**Comment by MarinAtanasov** [comment]
Thank you for the answer.
I would like to point out that I am not trying to be a jerk here. I am trying to help.
> Sure it does, LocalCache is an implementation of IDistributedCache that runs in memory.

Is it distributed? If not, it shouldn't implement IDistributedCache because it is confusing. Maybe the interface name is wrong, maybe it needs to extend something like ICache which could be a base interface of IDistributedCache.
> The major differences are the fact that IDistributedCache is async and requires a serialization mechanism.

The latter is an implementation detail which I do not necessarily need to know and makes the interface more difficult to use. It can use a binary serializer under the hood and a second constructor which allows you to pass in a custom one so that we can replace with protobuf or something else. This way the interface would not be restricted to using a byte[] value which in the case of LocalCache is a completely unnecessary overhead since it uses MemoryCache internally which works with objects anyway. LocalCache is a good example of how the interface is a problem. It if worked with objects, there would be no reason to use a binary serializer with it.

I am trying to make a caching layer which can be changed through a configuration. I thought about using IMemoryCache as a base interface, but this will limit me to an in-memory cache only. I decided to try using IDistributedCache but the fact that everyone who would need to get or set an item would need to have access to a binary serializer as well made it horrible to use. I figured that the solution would be to make a wrapper with a more usable interface which uses a binary serializer internally. The problem with that is that I shouldn't need to use a wrapper and fix the interface of a library which is not a legacy library that cannot be fixed because it would require breaking changes. If the interface is not made more usable by the time it gets out of beta, it will be just that - legacy code.

I might have been wrong about not having a binary serializer but all I have been able to find on binary serialization in .NET Core is [this post](https://github.com/dotnet/corefx/issues/1347#issuecomment-95249848). Could you tell me in which NuGet package are BinaryReader and BinaryWriter?

**Comment by davidfowl** [comment]
> I would like to point out that I am not trying to be a jerk here. I am trying to help.

Sure, no harm done. The tone is a bit odd for trying to help thought :wink: 

> Is it distributed? If not, it shouldn't implement IDistributedCache because it is confusing. Maybe the interface name is wrong, maybe it needs to extend something like ICache which could be a base interface of IDistributedCache.

A good analogy would be writing a unit test. The testable distributed cache isn't distributed either but it's all about the interface. The distributed cache and memory are different and will remain that way. You can use this as a decision point, if you want to cache to be shared across processes/instances/machines, whatever your unit of isolation is then you should code against the IDistributedCache interface. One again, you're coding against the interface, the LocalCache implementation is just something you would use if you wanted to code against the interface but have a default implementation that assumed you were in memory. It's so you can still function if you're running on one box without having to configure something like redis or sql server. 

> The latter is an implementation detail which I do not necessarily need to know and makes the interface more difficult to use. It can use a binary serializer under the hood and a second constructor which allows you to pass in a custom one so that we can replace with protobuf or something else. This way the interface would not be restricted to using a byte[] value which in the case of LocalCache is a completely unnecessary overhead since it uses MemoryCache internally which works with objects anyway. LocalCache is a good example of how the interface is a problem. It if worked with objects, there would be no reason to use a binary serializer with it.

It's a very large implementation detail, so large that it's in the interface. One thing we're not going to do again is try to serialize arbitrary object graphs into an off box cache. There's tons of considerations when taking serialization into account and it's up to customers to think about how their objects turn into byte[]. As for the LocalCache implementation being inefficient, sure you're right about that. It's less efficient than not serializing, but since it *does* use that code path you'll see if you have any problems with serialization earlier rather than later. Many times people assumed the things they were putting in the cache would *just work* when moving to an off box cache, and that turns rarely turns out to be the case. 


> I am trying to make a caching layer which can be changed through a configuration. I thought about using IMemoryCache as a base interface, but this will limit me to an in-memory cache only. I decided to try using IDistributedCache but the fact that everyone who would need to get or set an item would need to have access to a binary serializer as well made it horrible to use. I figured that the solution would be to make a wrapper with a more usable interface which uses a binary serializer internally. The problem with that is that I shouldn't need to use a wrapper and fix the interface of a library which is not a legacy library that cannot be fixed because it would require breaking changes. If the interface is not made more usable by the time it gets out of beta, it will be just that - legacy code.

I'm pretty sure we're not changing the interface at this point. The things you mention could be added in extension methods completely outside of the cache. See https://github.com/aspnet/Caching/pull/94.

> I might have been wrong about not having a binary serializer but all I have been able to find on binary serialization in .NET Core is this post. Could you tell me in which NuGet package are BinaryReader and BinaryWriter?

The System.IO package.

**Comment by MarinAtanasov** [comment]
Thank you for the quick answer and the links, David.
I understand now more of the reasoning behind the current implementation.

My main concern that remains is that if you need to use the caching in 5 different places in your implementation, you will need to have access to the serialization in those 5 places as well unless you wrap the IDistributedCache and the serializer in an object which is used instead. Extension methods would either hardcode the serializer being used or get it as a parameter in which case you will need access to a serializer everywhere again.

I am going to close this issue now. Please reconsider changing the interface and making an interface for a serializer that would be passed in through the constructor. This would make IDistributedCache much easier to use and clients will need to worry about the serializer only on creation.

**Comment by davidfowl** [comment]
> Please reconsider changing the interface and making an interface for a serializer that would be passed in through the constructor. This would make IDistributedCache much easier to use and clients will need to worry about the serializer only on creation.

We've discussed this several times and haven't really settled on anything. The design is such that it would be trivial to add an interface that sat in between user code and and the IDistributedCache that would be a convenience API for serializing/deserializing data. Nothing planned but it would be easy to do in the future.

**Comment by kwaclaw** [comment]
Why has the MemoryCache.AddOrGetExisting() API been removed? It allowed me to perform an atomic  Get or Add operation.

**Comment by Tratcher** [comment]
Because it wasn't actually atomic and was giving developers the wrong impression.

**Comment by MetalKid** [comment]
I believe the point being made here is similar to the one I'm running into now.  There should be one generic interface for both and the implementation can deal with the details.  Now if I have a project that I start with just Memory cache and after a while I realize I need to change to either distributed or Redis or something else, I have to go back and update ALL my code to use the other style instead of just changing it in one place (assuming the data being saved is serializable to a byte[]).  However, I also hate depending on 3rd party interfaces in core/common logic across my application (even if it is Microsoft).  Any change above and I end up screwed.  If we had 1 interface here, fixing that becomes much easier.  I will probably be abstracting both of these myself, but now I kind of have to merge 2 interface implementations that end up with the same result of just wanting to cache something.  Though, I do understand that the implementations are quite different and how the management of them is quite different.

**Comment by sebastienros** [comment]
> assuming the data being saved is serializable to a byte[]

Use the `IDistributedCache` interface then, not the memory cache. You won't have to change anything and you get a single interface.

> I also hate depending on 3rd party interfaces

You should create your own abstraction so you can use any other service whenever you need to. Even better, you can define many interfaces for each of your components. This will let you change the actual implementation for each of them.

**Comment by MetalKid** [comment]
I don't want to take the serialization hit if I don't have to.  In fact, I'd rather have a hybrid scenario where depending on the situation, one might go to memory while the other goes distributed (with the proper options that would end up preferring one or the other).  But it would be up to the implementation to decide where to put it.  Then again, this might be breaking SRP a bit, but the alternative is to essentially leak caching logic into your code base.

**Comment by sebastienros** [comment]
> I'd rather have a hybrid scenario where depending on the situation, one might go to memory while the other goes distributed

I like this too. This is why not so ironically I personally depend on `IMemoryCache` and other times `IDistributedCache`.

**Comment by MetalKid** [comment]
In your case, though, it sounds like the service is making the determination as to which cache to use.  I would say it is the cache's own responsibility to determine which to use, not the service's job.  If the service makes the decision, I feel like it knows too much.
