### ISSUE TITLE
Remove GC Compaction trigger

### ISSUE THREAD

**Issue by muratg** [aspnet/Caching#221]
@KKhurin @davidfowl 

Looks like we may have room for improvement here.

**Comment by muratg** [comment]
@KKhurin Are you able to help us with this?

**Comment by KKhurin** [comment]
Let's have a discussion.

**Comment by DamianEdwards** [comment]
I just hit what I think is a down side of the current implementation in that it appears we purge the cache on every Gen2 collection, which in my case was occurring during app start as I was forcibly priming my cache.

**Comment by JunTaoLuo** [comment]
Currently compaction is triggered by a gen2 collection by the GC. This is not the best trigger since it may occur frequently and does not correlate to the actual memory usage of the cache.

The proposal is to remove the current trigger and instead rely on the user or external triggers to decide when to compact the cache. This will require us to expose the Compact on the interface. Note that there's currently no way of accurately determining the memory usage by the cache so it's difficult to figure out if or how much compaction should occur.

**Comment by Eilon** [comment]
@JunTaoLuo can you update the bug title to reflect the decisions that were made (e.g. change Foo to X because Y).

**Comment by JunTaoLuo** [comment]
After the latest discussions, we decided to remove the memory compaction trigger based on Gen2 GC. To compact, downcast to `MemoryCache` and call `Compact` when needed.

**Comment by JunTaoLuo** [comment]
Will file follow up issue for revisiting the memory cache design.

**Comment by Eilon** [comment]
@JunTaoLuo is this change announcement-worthy?

**Comment by JunTaoLuo** [comment]
Yup that's why there is a breaking changes tag. Will get to it.

**Comment by muratg** [comment]
@JunTaoLuo Do you want to keep the bug open in that case?

**Comment by JunTaoLuo** [comment]
I will open a different issue in the Discussion milestone for the discussion to the announcement.

**Comment by code-mogwai** [comment]
Just checking the workaround for version 1.0.0 is to set CompactOnMemoryPressure to false for the MemoryCache instance?

(FYI, what we think we are experiencing as a result of this design bug is poor caching and only 30% memory utilisation on a server with 16GB RAM. Another server with 32GB RAM and the same application is also at 30% memory utilisation.)

**Comment by JunTaoLuo** [comment]
@code-mogwai yes, if this is affecting you, you should set `CompactOnMemoryPressure` to false. If you need to compact, you can downcast to `MemoryCache` and call `Compact` directly.
