### ISSUE TITLE
MemoryDistributedCache is not distributed

### ISSUE THREAD

**Issue by MatthewLymer** [aspnet/Caching#322]
I think that `MemoryDistributedCache` should be removed in its entirety and a no-op cache provider should be its replacement.

From the article https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed, it states: 

> A distributed cache is shared by multiple app servers (see Caching Basics). The information in the cache is not stored in the memory of individual web servers, and the cached data is available to all of the app's servers.

Furthermore, it seems that `MemoryDistributedCache` is the default implementation registered in the default dotnet core IoC container.

**Comment by rendmath** [comment]
Many application authors will not need (or want) to use an actual distributed caching solution (Redis, etc.). 

On the other side, library authors willing to provide distributed caching capabilities for their code will only want to use IDistributedCache if they can reasonably trust the IoC to give them an object with actual caching semantics. Otherwise, they won't use the interface at all and will revert to implementing library-specific caching mechanisms.

Therefore, bridging the MemoryCache as a "degenerate" distributed cache seems to be a very reasonable solution.

Of course, MemoryDistributedCache is not distributed at all. But in this case, the no-op "NullDistributedCache" that you are suggesting... wouldn't even be a cache at all. Couldn't it be considered worse, by your own criteria?

**Comment by JunTaoLuo** [comment]
The `MemoryDistributedCache` is not meant to be an actual distributed cache. It is meant to be a local `MemoryCache` based implementation that implements the `IDistributedCache` API. It is mainly designed to be a testing or debugging mechanism. The `MemoryDistributedCache` is no longer being added by default and an explicit call to `services.AddDistributedMemoryCache()` is required.
