### ISSUE TITLE
RegisterPostEvictionCallback is not a real event?

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/Caching#353]
Hello all

I'm bit confused about RegisterPostEvictionCallback. In old (and I'm start to be thinking "old good") ASP.NET we there able to use session event to clean up session (for instance, to Dispose and Disconnect. I know, using such objects are not really good, but you can address this to Microsoft PG's of different products who did such APIs).
Looks like in .NET Core this doesn't work at all. Session doesn't have event at all, but this is clear why.  MemoryCache have something similar (RegisterPostEvictionCallback) but it works very strange. It looks like this is not real event handler, but just some callback occurred or not without any real attach to event to time in the system.
Example. I have MemoryCacche item added with options:
```
TimeSpan defaultTimeout = new TimeSpan(0, 2, 0); 
var cacheEntryOptions = new MemoryCacheEntryOptions()
                            .SetSlidingExpiration(defaultTimeout)
                          .RegisterPostEvictionCallback(callback: (object key, object value, EvictionReason reason, object state) =>
                          {
                              tracer.WriteTrace(LogTraceLevel.Debug, "Cache item removed: {0}", key);
                          });
                        this.memoryCache.Set("SampleId", someObj, null);
```

But nothing happened after two minutes. Only when I sent an another request the callback executed. 
Questions:
1. Is it by design? If so, then what real benefits for such callback (except cache item dependencies)?
2. Any way to get real event when cache item expired?

**Comment by JunTaoLuo** [comment]
This is by design as the `PostEvicionCallback` is not an event. The callback is executed when the cache entry is removed from the cache, not on expiration. 

The removal of expired entries is done lazily after expiration upon an action on the cache. This is why the callback executed on your next request after expiration. For performance considerations we remove expired items in batches which has a minimum period specified by `MemoryCacheOptions.ExpirationScanFrequency`. 

We do not currently expose any mechanism to notify exactly when cache entries expire but expired entries will eventually trigger the expiration callback some time in the future after any cache operation.

**Comment by antonGritsenko** [comment]
Thank you for detailed explanation.
