### ISSUE TITLE
React to changes in StackExchange.Redis 2.0

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Caching#410]
Details at https://github.com/StackExchange/StackExchange.Redis/issues/871

I think we'd look at upgrading our dependency to 2.0 and knocking out the soon to be obsolete `StackExchange.Redis.StrongName` package in the 3.0 timeframe.

**Comment by BrennanConroy** [comment]
SignalR too?

**Comment by davidfowl** [comment]
Yep

**Comment by DamianEdwards** [comment]
Oh yeah

**Comment by NickCraver** [comment]
cc @mgravell

**Comment by HassanHashemi** [comment]
`StackExchange.Redis 2.0` is out, Given the perf improvements in StackExchange.Redis 2.0 It is tempting to backport this to `2.2-preview` or `2.2 release`?

**Comment by BrennanConroy** [comment]
>Is it https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/2.2.0-preview1-35029

Yes

**Comment by steveoh** [comment]
the nuget package name squatting is a problem. Thanks for the quick response!

**Comment by sadjadbp** [comment]
@DamianEdwards what about this repo https://github.com/aspnet/DataProtection is it needed to open a different issue there?

**Comment by dwilliss** [comment]
I see that this is scheduled for a 3.0 release, but is there any chance it could happen sooner?
There's a [memory leak issue ](https://github.com/StackExchange/StackExchange.Redis/issues/937#issuecomment-418681107) with the StackExchange.Redis.StrongName version 1.2 that appears to be solved in StackExchange.Redis version 2.0.

**Comment by NickCraver** [comment]
@DamianEdwards @davidfowl what are the chances for 2.2 here?

**Comment by niemyjski** [comment]
I'm broke because one dependency using 2.0 of the redis client and the Extensions.Caching.Redis is using v1... 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'ConnectionMultiplexer' exists in both 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, 
```

**Comment by niemyjski** [comment]
Please backport to 2.2....

**Comment by davidfowl** [comment]
@niemyjski backport? We haven't shipped 2.2 yet. I'm not sure it's reasonable to make this kind of breaking change in 2.2. We'll discuss it.

**Comment by niemyjski** [comment]
To bring the changes planned for 3.0 to 2.2 (upgrading redis). The redis client 2.0 changes have been stable for us but broke lots of things with the package name changing.

**Comment by 1amirjalai** [comment]
also time out issues get solved in stackexchange.redis 2.0.
it would be nice to see redis 2 on microsoft sooner

**Comment by buvinghausen** [comment]
@davidfowl I fully understand it's unreasonable to make this kind of change but we're about to yank Redis from our application due to ongoing issues.  We've had StackExchange.Redis 1.x make SignalR unusable on three separate occasions due to thread starvation from connectivity issues.  Obviously that means we will have to go down to one node and can no longer do no downtime deployments but I don't think I can keep our CEO at bay. Redis is literally a four letter word in his world at this point....

I really don't want to live in a single node world until sometime in 2019 if at all possible.

**Comment by Eilon** [comment]
I don't think it's OK to make such a breaking change in 2.2, but we can certainly create a new package that has the newer dependency and do that in 2.2. And then in 3.0 we'd stop building the old package.

Would that work?

**Comment by buvinghausen** [comment]
Being able to remove StackExchange.Redis 1.x by any means necessary in 2.2 would be better than waiting for 3.0

**Comment by robertmiles3** [comment]
I'm officially pulling Redis sessions from a Core app today because of major timeout issues. If possible, I'm cheering for a 2.2 on this one as well.

**Comment by Eilon** [comment]
@muratg - can we start a mail thread on this to see how we can proceed?

**Comment by buvinghausen** [comment]
Thanks @Eilon I sincerely appreciate you getting this started

**Comment by kevinsbennett** [comment]
Similar issues here.  I don't really care what we have to do to update to Redis 2.x, as long as there is a way.  We have a serious memory leak originating from this issue that was fixed in redis 2:   

https://github.com/StackExchange/StackExchange.Redis/pull/928

**Comment by effyteva** [comment]
+1

**Comment by AlonCG** [comment]
Thanks to all the devs that are working on this (and for all the work you do on all projects). 

Can we **please** though get a definitive, authoritative answer as to when this issue may be resolved?

Though I am sure it is not related, ever since patching in [CVE-2018-8409](https://github.com/aspnet/announcements/issues/316), our apps are getting increasing Redis connection issues causing our SessionCache to fail. I don't care if the app cache fails, since then it would fall over, but I have no fall-over for SessionCache failing.

If we don't know when this will be resolved, I will have to pull out Redis Sessions all together and come up with another application and session caching solution.

Again, thanks for all your time and efforts!

**Comment by moodmosaic** [comment]
>We have a serious memory leak originating from this issue that was fixed in redis 2:
>
>StackExchange/StackExchange.Redis#928

Same issue here.

---

What @Eilon suggests in https://github.com/aspnet/Caching/issues/410#issuecomment-422876276 would work fine:

>but we can certainly create a new package that has the newer dependency and do that in 2.2. And then in 3.0 we'd stop building the old package.

**Comment by muratg** [comment]
StackExchange released a new Redis library StackExchange.Redis V2.0.x

We'll be creating a new package: Microsoft.Extensions.Caching.StackExchange.Redis which uses that.

cc @anurse @Tratcher @DamianEdwards @Eilon

**Comment by effyteva** [comment]
> StackExchange released a new Redis library StackExchange.Redis V2.0.x
> 
> We'll be creating a new package: `Microsoft.Extensions.Caching.StackExchangeRedis` which uses that.
> 
> cc @anurse @Tratcher @DamianEdwards @Eilon

Planned for 2.2.0?

**Comment by davidfowl** [comment]
Yes

**Comment by effyteva** [comment]
Amazing, looking forward for the 2.2.0 release!

**Comment by BrennanConroy** [comment]
Fixed in https://github.com/aspnet/Caching/pull/424

**Comment by buvinghausen** [comment]
We will pick up the preview3 release and put it through the paces.

**Comment by muratg** [comment]
@buvinghausen Let us know if you see any issues! Thanks!
