### ISSUE TITLE
SqlServerCacheOptions doesn't implement the IOptions<SqlServerCacheOptions> interface

### ISSUE THREAD

**Issue by ehabelgindy** [aspnet/Caching#75]
Just noticed that the SqlServerCacheOptions doesn't implement the IOptions<SqlServerCacheOptions> interface following the same pattern used in the MemoryCacheOptions and RedisCacheOptions classes.

Is this a bug, or intentionally left like this?

**Comment by kichalla** [comment]
This was intentional. In general, you need not implement the `IOptions<>` interface as they get new'd up by a DI registered service called `OptionsManager`([this](https://github.com/aspnet/Options/blob/dev/src/Microsoft.Framework.OptionsModel/OptionsManager.cs#L40) line)

The `MemoryCacheOptions` and `RedisCacheOptions` classes implemented them to make testing easy as opposed to doing something like [this](https://github.com/aspnet/Caching/blob/dev/test/Microsoft.Framework.Caching.SqlServer.Tests/SqlServerCacheWithDatabaseTest.cs#L631) to enable calling like [this](https://github.com/aspnet/Caching/blob/dev/test/Microsoft.Framework.Caching.SqlServer.Tests/SqlServerCacheWithDatabaseTest.cs#L564).

**Comment by Tratcher** [comment]
@ehabelgindy is right, it's hard to instantiate multiple instances without this.

**Comment by muratg** [comment]
@kichalla Could you look into adding this?

**Comment by kichalla** [comment]
48da07494f82aaacce0e7cdccee1d4b0e5b21c9b
